<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="XE-T-DEEPAKS" ignored="0" name="Test2" tests="1" failures="1" timestamp="03 Aug 2017 17:07:21 GMT" time="36.589" errors="0">
  <testcase name="loginFunc" time="12.131" classname="test.LoginPageTest2">
    <failure type="java.lang.AssertionError" message="Expected: failed">
      <![CDATA[java.lang.AssertionError: Expected: failed
	at test.LoginPageTest2.loginFunc(LoginPageTest2.java:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- loginFunc -->
</testsuite> <!-- Test2 -->
